#!/bin/bash

DOT=$1 # path to .dots file

run()
{
  tput smcup # switch to alternate screen
  clear
  bin/dots $1
  tput rmcup # back to normal screen
}

help()
{
  echo "kqo's asciidots interpreter:
Usage: dots [options] path-to-circuit"
}

if [ -e "$DOT" ] # test the path
then
  run "$DOT"
else # path given won't work
  if [ ! -z "$DOT" ] # did they try to give a path
  then
    echo "File \"${DOT}\" not found."
  fi
  help
fi
